spring:
  datasource:
    url: jdbc:mysql://localhost:3306/atsast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root