spring:
  datasource:
    url: jdbc:mysql://pipe.sast.codes:7336/atsast?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST&useSSL=false&allowPublicKeyRetrieval=true
    username: atsast
    password: sast_forever
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.sast.atSast.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true